name: CI Pipeline MLOps

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          

      - name: Instalar dependências
        run: pip install -r requirements.txt 

      - name: Executar notebook Exploracao
        run: |
          jupyter nbconvert --to notebook --execute notebooks/01_exploracao.ipynb --output 01_exploracao_output.ipynb --output-dir notebooks

      - name: Executar notebook Validacao e Treino
        run: |
          jupyter nbconvert --to notebook --execute notebooks/02_pipeline_validacao.ipynb --output 02_pipeline_validacao_output.ipynb --output-dir notebooks
      - name: Commit e Push do modelo
        run: |
           git config --local user.email "action@github.com"
           git config --local user.name "GitHub Action"
           git add model.joblib vectorizer.joblib
           git commit -m "Novo modelo treinado [skip ci]" # [skip ci] evita loop infinito de builds
           git push
      - name: Executar notebook Monitoracao
        run: |
          jupyter nbconvert --to notebook --execute notebooks/04_monitorar_fairness.ipynb --output 04_monitorar_fairness_output.ipynb --output-dir notebooks
          
      - name: Rodar testes automatizados
        run: pytest test_pipeline.py
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build da imagem Docker
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/classificador-sentimentos:latest .

      - name: Push para Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/classificador-sentimentos:latest
